import type { Metadata } from "next";
import "./globals.css";
import { Alexandria } from "next/font/google";
import { Providers } from "@/providers";

const alexandria = Alexandria({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alexandria.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
